import { CardReveal, StackCard, WorkCard } from '@/types/types';
import {
	AlarmClockCheck,
	Bell,
	Book,
	BookMarked,
	Calendar,
	Code,
	CookingPot,
	FileClock,
	Folder,
	Gamepad2,
	Globe,
	HandHeart,
	Images,
	Info,
	KeyRound,
	Mail,
	Map,
	MapPin,
	MessageSquare,
	Newspaper,
	Palette,
	PencilRuler,
	Save,
	Tags,
	Trash,
	UserPlus,
	UserSearch,
	UsersRound,
	Workflow,
} from 'lucide-react';

export const SITE_NAME = 'Sepetowski';
export const MY_EMAIL = 'jakubsepetowskipraca@gmail.com';

export const MY_ALL_WORKS: WorkCard[] = [
	{
		title: 'STUDY_FLOW.TITLE',
		subtitle: 'STUDY_FLOW.SUBTITLE',
		alt: 'STUDY_FLOW.ALT',
		linkHref: '/work/StudyFlow',
		src: '/images/studyFlow/studyFlow6',
		hasDarkMorde: true,
	},
	{
		title: 'KIVI.TITLE',
		subtitle: 'KIVI.SUBTITLE',
		alt: 'KIVI.ALT',
		linkHref: '/work/Kivi',
		src: '/images/kivi/kivi',
		hasDarkMorde: true,
	},
	{
		title: 'MY_PORTFOLIO.TITLE',
		subtitle: 'MY_PORTFOLIO.SUBTITLE',
		alt: 'MY_PORTFOLIO.ALT',
		linkHref: '/work/Portfolio',
		src: '/images/portfolio/portfolio',
		hasDarkMorde: true,
	},
	{
		title: 'JUST_NOTED.TITLE',
		subtitle: 'JUST_NOTED.SUBTITLE',
		alt: 'JUST_NOTED.ALT',
		linkHref: '/work/JustNoted',
		src: '/images/justNoted/justNoted.png',
	},

	{
		title: 'NATALIA_SITE.TITLE',
		subtitle: 'NATALIA_SITE.SUBTITLE',
		alt: 'NATALIA_SITE.ALT',
		linkHref: '/work/Natalia-website',
		src: '/images/NataliaWebsite/nataliaSite.png',
	},
	{
		title: 'TRAVEL_MARK.TITLE',
		subtitle: 'TRAVEL_MARK.SUBTITLE',
		alt: 'TRAVEL_MARK.ALT',
		linkHref: '/work/TravelMark',
		src: '/images/travelMark/travelMark.png',
	},
	{
		title: 'RECIPE_APP.TITLE',
		subtitle: 'RECIPE_APP.SUBTITLE',
		alt: 'RECIPE_APP.ALT',
		linkHref: '/work/Recipe-App',
		src: '/images/recipeApp/recipeApp.png',
	},
	{
		title: 'GN_NEWS.TITLE',
		subtitle: 'GN_NEWS.SUBTITLE',
		alt: 'GN_NEWS.ALT',
		linkHref: '/work/GnNews',
		src: '/images/gnNews/gnNews',
		hasDarkMorde: true,
	},
];

export const MY_STACK: StackCard[] = [
	{ alt: 'HTML', src: '/svg/html.svg' },
	{ alt: 'CSS', src: '/svg/css.svg' },
	{ alt: 'SASS', src: '/svg/sass.svg' },
	{ alt: 'Tailwindcss', src: '/svg/tailwindcss.svg' },
	{ alt: 'Shadcn', src: '/svg/shadcn.svg', needBgc: true },
	{ alt: 'JavaScript', src: '/svg/js.svg' },
	{ alt: 'TypeScript', src: '/svg/ts.svg' },
	{ alt: 'C#', src: '/svg/c4.svg' },
	{ alt: 'React', src: '/svg/react.svg' },
	{ alt: 'Next.js', src: '/svg/nextjs.svg', needBgc: true },
	{ alt: 'Zod', src: '/svg/zod.svg' },
	{ alt: 'Zustand', src: '/images/zustand.png' },
	{ alt: 'Framer motion', src: '/svg/framerMotion.svg' },
	{ alt: 'React Router', src: '/svg/router.svg', needBgc: true },
	{ alt: 'React Redux', src: '/svg/redux.svg' },
	{ alt: 'React Flow', src: '/svg/reactFlow.svg', needBgc: true },
	{ alt: 'TanStack Query', src: '/svg/reactQuery.svg' },
	{ alt: 'Axios', src: '/svg/axios.svg' },
	{ alt: 'Prisma', src: '/svg/prisma.svg', needBgc: true },
	{ alt: 'PostgreSQL', src: '/svg/postgreSql.svg' },
	{ alt: 'NextAuth.js', src: '/images/nextAuth.png' },
	{ alt: 'Firebase', src: '/svg/firebase.svg' },
	{ alt: 'Supabase', src: '/svg/supabase.svg', needBgc: true },
	{ alt: 'Pusher', src: '/images/pusher.png', needBgc: true },
	{ alt: 'Npm', src: '/svg/npm.svg' },
	{ alt: 'Git', src: '/svg/git.svg' },
	{ alt: 'Github', src: '/svg/github.svg', needBgc: true },
	{ alt: 'Vite', src: '/svg/vitejs.svg' },
	{ alt: 'Visual Studio Code', src: '/svg/vscode.svg' },
	{ alt: 'Visual Studio', src: '/svg/viusalStudio.svg' },
];

export const ABOUT_ME_CARDS: CardReveal[] = [
	{
		title: 'STUDENT.TITLE',
		desc: 'STUDENT.DESC',
		Icon: Book,
	},
	{
		title: 'HOBBY.TITLE',
		desc: 'HOBBY.DESC',
		Icon: Gamepad2,
	},
	{
		title: 'PROGRAMMING.TITLE',
		desc: 'PROGRAMMING.DESC',
		Icon: Code,
	},
];

export const FEATURES_ICONS = [
	{
		title: 'StudyFlow',
		icons: [
			KeyRound,
			Globe,
			UsersRound,
			Folder,
			Workflow,
			PencilRuler,
			MessageSquare,
			Calendar,
			AlarmClockCheck,
			Bell,
			Tags,
			UserPlus,
		],
	},
	{
		title: 'Kivi',
		icons: [
			KeyRound,
			UsersRound,
			Images,
			HandHeart,
			Palette,
			MessageSquare,
			Bell,
			UserSearch,
			BookMarked,
		],
	},
	{
		title: 'Portfolio',
		icons: [Globe, Palette, Mail],
	},
	{
		title: 'JustNoted',
		icons: [KeyRound, Palette, PencilRuler, FileClock, Calendar, Trash],
	},
	{
		title: 'Natalia-website',
		icons: [Images],
	},
	{
		title: 'TravelMark',
		icons: [Map, Globe, MapPin],
	},
	{
		title: 'Recipe-App',
		icons: [CookingPot, Save, Info],
	},
	{
		title: 'GnNews',
		icons: [Newspaper],
	},
];
